### ISSUE TITLE
Windows 工具 | Lantern's 小站

### ISSUE THREAD

**Issue by Lantern-r** [Lantern-r/Lantern-r.github.io#48]
https://lantern.cool/2020/07/15/tool-useful-tools/ 

 想到就写进去。 utools: 类似wox scrcpy: 电脑通过usb控制手机 Qtscrpy: 基于上面工具开发的qt界面 snipaste: 截图/贴图工具 Clash: 代理分流工具

**Comment by Macline564** [comment]
来空间踩踩
